Javascript Group Capstone Project
anshuman7negi/Kanban_board pull request #54
Opened 2023-08-03 12:38 UTC by Bupilipili

2023-08-03 14:07 UTC, Bupilipili commented
Note: To run this project on your local device you are required to erase all the public path in webpackconfig.js file into this(public path"./") since if the public path remains like this the deployment doesn't show the javascript and the CSS of the code.

2023-08-03 14:41 UTC, elisha2kyakpo1 requested changes
Hi 👋 @Bupilipili, @anshuman7negi, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

✔️ The PR title and description are good and professional.
✔️ No linter errors.
✔️ Descriptive readme file.
✔️ Tests passing👏
👏 The app works as expected.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-03 14:41 UTC, elisha2kyakpo1 commented on src/modules/popupCard.js
> +/* eslint-disable linebreak-style */
- [x] Kindly do not disable linters, linters are used to highlight errors in our code. The errors should be fixed to have a clean code that meets standards.

2023-08-03 14:41 UTC, elisha2kyakpo1 commented on src/testing/itemsCounter.test.js
> +// Import the function to test
Kindly do not disable linters, linters is used to highlight errors in our code. The errors should be fixed to have a clean code that meets standards.

2023-08-03 14:41 UTC, elisha2kyakpo1 commented on README.md
> +
- [ ] Great job recording the video, unfortunately, it did not meet the requirements for this project. Kindly record another video and remember to follow all the requirements for the video.


![video](https://github.com/anshuman7negi/Kanban_board/assets/53124548/a935a04d-3c65-4dfb-bdfb-4c8a08cf539e)

2023-08-04 05:10 UTC, Bupilipili commented on src/modules/popupCard.js
> +/* eslint-disable linebreak-style */
Alright i have fixed it.

2023-08-04 05:10 UTC, Bupilipili commented on src/testing/itemsCounter.test.js
> +// Import the function to test
I also fixed it.

2023-08-04 09:31 UTC, LionRouge1 approved these changes
Hi **Team**, 

# STATUS: APPROVED! 🥇 💯 
Great work on making the changes 👏 
You've done well implementing the requested changes

![done](https://media.giphy.com/media/3o7abKhOpu0NwenH3O/giphy.gif)

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:

## Highlights
- Great job, your project is error free :+1: 
- Nice work you meet all the requirements :1st_place_medal: 
- All linters passed :heavy_check_mark: 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2023-08-04 10:19 UTC, merged